### ISSUE TITLE
КАК ЭТО СОБРАТЬ?

### ISSUE THREAD

**Issue by userwindows10mobile** [mediaexplorer74/YoutubeApp#1]
?

**Comment by mediaexplorer74** [comment]
Солюшн совместим с Visual Studio 2022 Community. Или VS 2017 Community. Я в readme написал, что проект оформлен "как есть", без консультирования по сборке и паблишингу appx пакетов, ну и без поддержки. Разработчик сам должен гуглить, что делать с sln файлом, а также как собирать проекты. Еще StackOverflow (с яндекс-переводчиком) рулит для ответов на любой программерский вопрос. Вообщем, как то так.
